services:
  - type: web
    name: ecc-price-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: ENABLE_LOCAL_HTTPS
        value: "0"
      - key: APP_USERNAME
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: MORLEVI_PASSWORD
        sync: false
      - key: CRG_PASSWORD
        sync: false
